project_id: 683600
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /changelog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog-changelog/**/%original_file_name%
